services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3001:3001'
    volumes:
      - shared-data:/results
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge
