services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '5173:5173'
    volumes:
      - shared-data:/results
    networks:
      - app-network

volumes:
  shared-data:

networks:
  app-network:
    driver: bridge
