name: Secure CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with security plugins
        run: |
          npx eslint . --ext .ts,.js

      - name: Run npm audit for known vulnerabilities
        run: |
          npm audit --audit-level=moderate || true

      - name: Build Docker image
        run: docker build -t linkcheck-image -f Dockerfile .

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: linkcheck-image
          format: 'table'
          severity: 'CRITICAL,HIGH'

  # dast-scan:
  #   runs-on: ubuntu-latest
  #   needs: security-pipeline

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Start Docker services
  #     run: docker-compose up -d

  #   # Optional placeholder for future frontend DAST scan
  #   - name: Run OWASP ZAP Baseline Scan (optional)
  #     uses: zaproxy/action-baseline@v0.9.0
  #     with:
  #       target: 'http://localhost:3000'  # TODO: Update with proper URL
  #     continue-on-error: true
